apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/neetika-sri/sample-jenkins-project:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/neetika-sri/sample-jenkins-project:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: sample-jenkins-project
        chartPath: charts/sample-jenkins-project
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/neetika-sri/sample-jenkins-project"
          image.tag: "{{.DIGEST_HEX}}"
